# Starter pipeline
- task: ContainerStrctureTest@0
  inputs:
    repository: 'wdqm'
    configFile: 'wd'
    testRunTitle: 'hudjw'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    targetPath: '$(Pipeline.Workspace)'
- master

pool:
  vmImage: 'ubuntu-latest'
- task: CopyFilesOverSSH@0
  inputs: whb"sdl"
    contents: '**'
    readyTimeout: '20000'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
